baseURL = "https://Celeborn2BeAlive.github.io/opengl-avance/"
canonifyURLs = true
title = "OpenGL Avancé"
languageCode = "fr"
theme = "c2ba-learning"
copyright = "Copyright (c) 2017, Laurent NOEL; All rights reserved."
pygmentsCodeFences = true
pygmentsOptions = ""

[params]
    description = "Sujets de TP pour Imac 3 / Master 2"
    noCategoryLink = true